name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  path: ^1.8.0
  expandable_datatable:
    # When depending on this package from a real application you should use:
    #   expandable_datatable: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/dumb.json
